spring:
  redis:
    redisson:
      config: |
        singleServerConfig:
          password: 123456
          address: "redis://192.168.50.238:6379"
          database: 1
        threads: 0
        nettyThreads: 0
        transportMode: "NIO"

  application:
    name: stock
  datasource:
    amazon:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: toor0109
      jdbc-url: jdbc:mysql://192.168.50.238:3306/db_wimoor
      username: root
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      minEvictableIdleTimeMillis: 300000
      poolPreparedStatements: true
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      validationQuery: SELECT 1 FROM DUAL
    stock:
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: toor0109
      jdbc-url: jdbc:mysql://localhost:3306/stock
      username: root
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      minEvictableIdleTimeMillis: 300000
      poolPreparedStatements: true
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      validationQuery: SELECT 1 FROM DUAL
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          enable_lazy_load_no_trans: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      database: mysql
      show-sql: true
      generate-ddl: false
  data:
    redis:
      password: 123456
      port: 6379
      host: 192.168.50.238

server:
  port: 32888
xxl:
  job:
    admin:
      addresses: http://192.168.50.238:8080/xxl-job-admin
    executor:
      appname: stock-executor
      port: 30888
      ip: 192.168.50.231
      logpath: /tmp/applogs/xxl-job/jobhandler
      logretentiondays: 30
    accessToken: default_token
thread:
  pool:
    coreSize: 8
    maxSize: 8
    queueSize: 0
    threadNamePrefix: stock-job-async