xpaths:
  accountInput: "//*[@id=\"container\"]/div/div[2]/form/div/div[1]/div[1]/input"
  passwordInput: "//*[@id=\"container\"]/div/div[2]/form/div/div[1]/div[2]/input"
  loginButton: "/html/body/div[2]/div/div[2]/div/div[2]/form/div/div[2]/div[1]/button"
  accountVerifyButton: "/html/body/div[2]/div/div[2]/div/div[2]/ul/li"
  verifyEmailSendButton: "/html/body/div[2]/div/div[2]/div/div[2]/div/div[3]/div[2]/button"
  verifyEmailCodeInput: "/html/body/div[2]/div/div[2]/div/div[2]/div/div[3]/div[1]/input"
  verifySubmitButton: "/html/body/div[2]/div/div[2]/div/div[2]/div/div[4]/button"
  selectAllCartItemsDiv: "/html/body/div[2]/div/div[2]/div/div/div[1]/div[1]/div[1]/div/div/div[1]"
  selectAllCartItemsButton: "//*[@id=\"listHeader_H\"]/div/div/div[1]/label/input"
  subtotalDiv: "//*[@id=\"rightContainer_CR\"]/div/div[2]/div/div[1]/div[1]/div/div[2]"
  shippingFeeDiv: "//*[@id=\"rightContainer_CR\"]/div/div[2]/div/div[1]/div[2]/div/div[2]"
  totalPriceDiv: "//*[@id=\"rightContainer_CR\"]/div/div[2]/div/div[3]/div/div[2]"
  checkoutButton: "//*[@id=\"rightContainer_CR\"]/div/div[2]/div/div[3]/button"
urls:
  loginPage: "https://member.lazada.sg/user/login"
  addToCartApi: "https://cart.lazada.sg/cart/api/add"
  cartPage: "https://cart.lazada.sg/cart"
  placeOrderPage: "https://checkout.lazada.sg/shipping"
  listAddressApi: "https://member.lazada.sg/address/api/listAddress"
  getByPostCodeApi: "https://member.lazada.sg/locationtree/api/getByPostCode"
  validatePhoneApi: "https://member.lazada.sg/user/api/validatePhone"
  createAddressApi: "https://member.lazada.sg/address/api/createAddress"
  deleteAddressApi: "https://member.lazada.sg/address/api/deleteAddress"
  logisticViewPage: "https://my.lazada.sg/customer/logisticDetail/view"
  cartCountApi: "https://cart.lazada.sg/cart/api/count"